apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
    meta.helm.sh/release-name: apim-devportal
    meta.helm.sh/release-namespace: apim-devportal
  creationTimestamp: "2022-02-09T00:24:16Z"
  generation: 4
  labels:
    app.kubernetes.io/component: apiportal
    app.kubernetes.io/instance: apim-devportal
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: axway-apim-apiportal
    app.kubernetes.io/version: "1.0"
    helm.sh/chart: axway-apim-2.3.0
  name: axway-apim-apiportal
  namespace: apim-devportal
  resourceVersion: "4477122"
  uid: 42fa1649-0993-4752-a891-e237baf291df
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: apiportal
      app.kubernetes.io/instance: apim-devportal
      app.kubernetes.io/name: axway-apim-apiportal
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: apiportal
        app.kubernetes.io/instance: apim-devportal
        app.kubernetes.io/name: axway-apim-apiportal
      name: axway-apim-apiportal
    spec:
      containers:
      - env:
        - name: MYSQL_HOST
          value: mysqlapiportal
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_DATABASE
          value: apiportal
        - name: MYSQL_USER
          value: report
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mysql-password
              name: mysqlapiportal
        - name: APIMANAGER_CONFIGURED
          value: "1"
        - name: APIMANAGER_NAME
          value: master
        - name: APIMANAGER_HOST
          value: apimgr
        - name: APIMANAGER_PORT
          value: "8075"
        - name: APACHE_SSL_ON
          value: "1"
        - name: APACHE_SSL_CERT
          valueFrom:
            secretKeyRef:
              key: apache.crt
              name: axway-apim-apiportal-certificates
        - name: APACHE_SSL_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              key: apache.key
              name: axway-apim-apiportal-certificates
        image: docker.io/axwayaustralia/apim-demo-apiportal_202111:1.2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            httpHeaders:
            - name: k8sprobe
              value: liveness.apiportal
            path: /
            port: apiportal
            scheme: HTTPS
          initialDelaySeconds: 60
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 5
        name: axway-apim-apiportal
        ports:
        - containerPort: 443
          name: apiportal
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            httpHeaders:
            - name: k8sprobe
              value: readiness.apiportal
            path: /
            port: apiportal
            scheme: HTTPS
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 500m
            memory: 1000Mi
          requests:
            cpu: 100m
            memory: 500Mi
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/axway/apiportal/enckey
          name: enckey
        - mountPath: /opt/axway/apiportal/htdoc/images
          name: images
        - mountPath: /opt/axway/apiportal/htdoc/language
          name: language
        - mountPath: /opt/axway/apiportal/htdoc/templates
          name: templates
        - mountPath: /opt/axway/apiportal/htdoc/administrator/language
          name: admlanguage
        - mountPath: /opt/axway/apiportal/htdoc/administrator/components/com_apiportal/assets/cert
          name: certs
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - sh
        - -c
        - until nc -w 3 -v mysqlapiportal 3306; do echo waiting for apiportal mysql;
          sleep 2; done;
        image: busybox:1.33
        imagePullPolicy: IfNotPresent
        name: init-mysql-apiportal
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - command:
        - sh
        - -c
        - until nc -w 3 -v apimgr 8075; do echo waiting for apimgr; sleep 2; done;
        image: busybox:1.33
        imagePullPolicy: IfNotPresent
        name: init-apimgmt
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1048
        runAsUser: 1048
      terminationGracePeriodSeconds: 30
      volumes:
      - name: enckey
        persistentVolumeClaim:
          claimName: apiportal-enckey
      - name: images
        persistentVolumeClaim:
          claimName: apiportal-images
      - name: language
        persistentVolumeClaim:
          claimName: apiportal-language
      - name: templates
        persistentVolumeClaim:
          claimName: apiportal-templates
      - name: admlanguage
        persistentVolumeClaim:
          claimName: apiportal-adm-language
      - name: certs
        persistentVolumeClaim:
          claimName: apiportal-certs
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-02-10T00:43:31Z"
    lastUpdateTime: "2022-02-10T00:43:31Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-02-10T00:43:01Z"
    lastUpdateTime: "2022-02-10T00:43:31Z"
    message: ReplicaSet "axway-apim-apiportal-86c5fddcd4" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 4
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
